### PR TITLE
EquilibriumIndex - Solved - Vinoth

### PR DESCRIPTION
**Pull request by vinothje**
Question 3
Equilibrium index of an array is an index such that the sum of elements at lower indexes is equal to
the sum of elements at higher indexes. For example, in an arrya A:
A[0] = -7, A[1] = 1, A[2] = 5, A[3] = 2, A[4] = -4, A[5] = 3, A[6]=0
3 is an equilibrium index, because:
A[0] + A[1] + A[2] = A[4] + A[5] + A[6]
6 is also an equilibrium index, because sum of zero elements is zero,
i.e., A[0] + A[1] + A[2] + A[3] + A[4] + A[5]=0
7 is not an equilibrium index, because it is not a valid index of array A.
Write a function int equilibrium(int[] arr, int n); that given a sequence arr[] of size n,
returns an equilibrium index (if any) or -1 if no equilibrium indexes exist.

### CODE REVIEW

**Comment by chandramouly** [comment]
good attempt Vinoth! can you try to solve in one iteration without computing total?

**Comment by vinothje** [comment]
@chandramouly , you could go as hiring manager :) sure will do it.

**Comment by chandramouly** [comment]
@vinothje  - nothing like that, I am learning as u are. these are the questions they will ask us in the interview..so pls dont take my comments serious :) 👍

**Comment by vinothje** [comment]
@chandramouly , no machi i really liked your review comments. Exactly the same way the interview guys are asking. That's why i said like that :) I want those kinda review comments so that i can improvise as well. I will post my interview questions as well in icebreakers.

**Comment by chandramouly** [comment]
No worries, got it.. 👍  Yes please post it, even it will be helpful for me..

**Pull request closed without merging**
