### PR TITLE
NumbersCount Solved - Vinoth

### PR DESCRIPTION
**Pull request by vinothje**

### CODE REVIEW

**Comment by vinothje** [comment]
Please review

**Review by vinothje — COMMENTED** [review]
Please review.

**Comment by chandramouly** [comment]
@vinothje  try running for the following inputs
empty string
null string
abc

Also see if you need TreeMap and as well as additional array, just one of them will be enough?
try to simplify the code, write less lines of code is the key..

but you gave a very good attempt! the program prints the output correctly... what i mentioned above was just scope for improvement...

**Comment by balamuralim** [comment]
Appreciate your efforts to solve this Vinoth :) Praveen wanted it to be solved using recursion. Can try solving using recursion?

**Comment by vinothje** [comment]
Solved via recursion.

https://github.com/breaktheice/Assignments/pull/37

Also taken care of  null, empty and other invalid inputs.

**Comment by vinothje** [comment]
Thanks Mouly and Bala for the review. Please check my code with recursion below.
https://github.com/breaktheice/Assignments/pull/37

**Pull request closed without merging**
