### PR TITLE
NumbersCount - Solved Recursion - Vinoth

### PR DESCRIPTION
**Pull request by vinothje**
Solved via Recursion.

### CODE REVIEW

**Review by chandramouly — COMMENTED** [review]
Great, looks good..
I was looking for the size of your array, now you put 10, which is good. But do you think you need map of size N??? I will also put my solution, you can take a look..  say if you have the string length of 1million, we are unnecessarily creating a map

**Comment by vinothje** [comment]
Mouly,Dont post your solution...Hang on. I got the idea. one moment.

**Comment by vinothje** [comment]
Mouly, Please review now. I removed the HashMap.  I was getting used to use HashMap for all my problems.

**Comment by balamuralim** [comment]
👍 Perfect Solution Vinoth

**Pull request closed without merging**
